version: '2.1'
volumes:
  apk-build:
services: 
  mysql:
    image: mysql:5.6
    container_name: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - DATABASE_HOST=mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  server:
    container_name: server
    image: server
    build:
      context: ""
      dockerfile: server/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
          condition: service_healthy
  mobile_user:
    container_name: mobile_user
    image: mobile_user
    volumes:
      - apk-build:/usr/src/app
    build:
      context: ""
      dockerfile: mobile/Dockerfile
  front:
    container_name: client_web
    image: client_web
    volumes:
      - apk-build:/app
    build:
      context: ""
      dockerfile: front/Dockerfile
    ports:
        - 8081:80
    depends_on:
      - server
      - mobile_user